=== tmg24aqua/Study-1-semestr/KYAR/lab12/shop.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="shop">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title1" type="xs:string"/>
        <xs:element name="heading">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cap1" type="xs:string"/>
              <xs:element name="cap2" type="xs:string"/>
              <xs:element name="cap3" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="product" maxOccurs="5">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="price" type="xs:string"/>
              <xs:element name="characteristics" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tmg24aqua/Study-1-semestr/KYAR/lab12/third.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="forXML.css"?>
<shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="shop.xsd">
<title1>Интернет-магазин</title1>
<heading>
<cap1>Название</cap1>
<cap2>Цена</cap2>
<cap3>Характеристики</cap3>
</heading>
 <product>
        <name>Apple MacBook Air 13" M1 2020 3,2 Мгц, 8 GB, 256 GB SSD, «Space Gray» [MGN63]</name>
        <price>2550 BYN</price>
        <characteristics>Ноутбук Apple MacBook Air 13 M1 (2020) 8/256GB Space Gray (MGN63) оснащен восьмиядерным процессором M1, который рационально распределяет задачи между ядрами, обеспечивает оптимальную производительность при запуске ресурсоемких программ, редактировании мультимедийных материалов. Видеокарта эффективно обрабатывает графическую информацию. За счет этого в динамичных сценах не образуются разрывы кадров, зависания. Устройство имеет дисплей Retina с разрешением 2450x1600 пикселей, на который выводит детализированные изображения с реалистичной цветопередачей для комфортного просмотра контента.</characteristics>
</product>
 <product>
        <name>Apple Mac Mini M4 MU9D3</name>
        <price>3000 BYN</price>
        <characteristics>Новый Mac mini уже здесь – еще более компактный и мощный. Всего 12,7 x 12,7 см, но поражает своей производительностью. Обновленный дизайн построен вокруг чипа Apple, чтобы максимально использовать возможности M4 и M4 Pro. Большое количество портов спереди и сзади позволяет подключать все необходимые устройства. Mac mini не только изменяет представление об эффективности, но становится первым компьютером Mac с нулевым уровнем выбросов CO. Маленький, но очень мощный.</characteristics>
</product>
  <product>
        <name>Macbook Air 13" M2 2022 256 GB Тёмная ночь MLY33</name>
        <price>3310 BYN</price>
        <characteristics>Абсолютно новый.Полностью обновленный MacBook Air теперь работает на чипе M2 нового поколения, обеспечивая необычайную скорость и энергоэффективность в новом, необыкновенно тонком, полностью алюминиевом корпусе. MacBook Air позволит вам играть, работать, создавать что угодно и где угодно. Благодаря обновленному чипу M2 ноутбук обеспечивает невероятную производительность без вентилятора, поэтому MacBook Air работает совершенно бесшумно, вне зависимости от сложности задачи.</characteristics>
</product>
  <product>
        <name>Macbook Air 13" M3 2024 256 GB Тёмная ночь MRXV3</name>
        <price>3810 BYN</price>
        <characteristics>Современный ноутбук Apple MacBook Air 13 с лёгкостью справляется с рабочими задачами и развлечениями. Встроенный чип M3 обеспечивает больше возможностей и продвинутых функций для искусственного интеллекта. Аудиосистема нового MacBook Air 13 отличается широким стерео звучанием и поддержкой системы звука в многоканальном режиме. Для наушников предусмотрен выход 3,5 мм.</characteristics>
</product>   
 <product>
        <name>
MacBook Pro 16" M3 Max: 48 ГБ, SSD 1 TB, Чёрный космос MUW63</name>
        <price>11900  BYN</price>
        <characteristics>Новое поколение MacBook Pro 16" действительно приносит в мир высокотехнологичных ноутбуков множество потрясающих обновлений, делая его идеальным компаньоном для профессионалов и творческих личностей.
Основным изменением в линейке MacBook Pro 16" стали мощные чипы M3 Pro и M3 Max. Эти чипы, созданные по передовой 3-нанометровой технологии, открывают новые горизонты производительности. Графический процессор получил не только обновленную архитектуру, но и динамическое кэширование, что существенно улучшает использование графического потенциала ноутбука.</characteristics>
</product>    
 </shop>
